---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Don Le dhl595

#### Introduction 

```{R}

install.packages('KableExtra', dependencies=TRUE, repos='http://cran.rstudio.com/')

library(kableExtra)

library(tidyverse)
library(dplyr)
Hypertension_mortality_by_state <- read_csv("Hypertension_mortality_by_state.csv")
Heart_disease_mortality_by_state <- read_csv("Heart_disease_mortality_by_state.csv")
```


Paragraph or two introducing your datasets and variables, why they are interesting to you, etc.

```{R}
# read your datasets in here, e.g., with read_csv()

```

#### Tidying: Reshaping

If your datasets are tidy already, demonstrate that you can reshape data with pivot wider/longer here (e.g., untidy and then retidy). Alternatively, it may be easier to wait until the wrangling section so you can reshape your summary statistics. Note here if you are going to do this.

```{R}
Heart_disease_mortality_by_state <- Heart_disease_mortality_by_state %>% pivot_wider(names_from = STATE, values_from = RATE)
Hypertension_mortality_by_state <- Hypertension_mortality_by_state %>% pivot_wider(names_from = STATE, values_from = RATE)

Heart_disease_mortality_by_state <- Heart_disease_mortality_by_state %>% pivot_longer(4:54, names_to = "STATE", values_to = "Heart_Disease_Mortality_per_100000_People", values_drop_na = TRUE)
Hypertension_mortality_by_state <- Hypertension_mortality_by_state %>% pivot_longer(4:54, names_to = "STATE", values_to = "Hypertension_Mortality_per_100000_People", values_drop_na = TRUE)
```


```{R}
Heart_disease_mortality_by_state <- Heart_disease_mortality_by_state %>% rename(Heart_Disease_Deaths = "DEATHS") %>% select(.,-URL)
Hypertension_mortality_by_state <- Hypertension_mortality_by_state %>% rename(Hypertension_Deaths = "DEATHS") %>% select(.,-URL)

```

    
#### Joining/Merging

```{R}
Mortality_joined <- inner_join(Heart_disease_mortality_by_state, Hypertension_mortality_by_state, by = c("STATE" = "STATE", "YEAR" = "YEAR"))

Mortality_joined <- Mortality_joined[c("YEAR", "STATE", "Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People")]

Heart_disease_mortality_by_state %>% n_distinct()
Hypertension_mortality_by_state %>% n_distinct()

Heart_disease_mortality_by_state %>% nrow()
Hypertension_mortality_by_state %>% nrow()


anti_join(Heart_disease_mortality_by_state, Hypertension_mortality_by_state) %>% n_distinct()
anti_join(Hypertension_mortality_by_state, Heart_disease_mortality_by_state) %>% n_distinct()

nrow(Mortality_joined)

350-350
# your joining code
```

Discussions of joining here. Feel encouraged to break up into more than once code chunk and discuss each in turn.

####  Wrangling

```{R - Core dplyr functions} 
Mortality_joined %>% filter(STATE == "AL")

Mortality_joined %>% select(`Heart_Disease_Deaths`)

Mortality_joined %>% arrange(desc('Heart_Disease_Mortality_per_100000_People'))

Mortality_joined %>% group_by(STATE)

Mortality_joined %>% mutate(Heart_Disease_Mortality_per_10000_People = (Heart_Disease_Mortality_per_100000_People)/10)

Mortality_joined %>% mutate(Hypertension_Mortality_per_10000_People = (Hypertension_Mortality_per_100000_People)/10)

Mortality_joined %>% summarize(mean(Heart_Disease_Deaths > 5000))

```
```{R - dplyr Summary Statistics Overall}
#5 unique functions
Mortality_joined %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), mean)
  
Mortality_joined %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), sd)

Mortality_joined %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), min)

Mortality_joined %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), max)

Mortality_joined %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), median)

#2 functions using Group by categorical variable
Mortality_joined %>% group_by(STATE, YEAR) %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), mean)
  
Mortality_joined %>% group_by(YEAR) %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), sd)

#define my own function
Per_10000 <- function(x) {
  value <- x/10
  return(value)
}

Mortality_joined %>% group_by(STATE) %>% summarize(Heart_Disease_Mortality_per_10000_People = Per_10000(Heart_Disease_Mortality_per_100000_People))

#n() inside group_by
Mortality_joined %>% group_by(STATE) %>% summarize(Heart_Disease_and_Hypertension_Count = n())
Mortality_joined %>% group_by(YEAR) %>% summarize(Heart_Disease_and_Hypertension_Count = n())

#table using kable

Mortality_joined %>% group_by(YEAR) %>% summarize_at(c("Heart_Disease_Deaths", "Heart_Disease_Mortality_per_100000_People", "Hypertension_Deaths", "Hypertension_Mortality_per_100000_People"), sd) %>% kbl() %>% kable_material_dark()

#table using pivot_wider that can be used to make a table using kable package
Mortality_joined %>% pivot_wider(names_from = YEAR, values_from = Heart_Disease_Deaths)
```


Your discussion of wrangling section here. Feel encouraged to break up into more than once code chunk and discuss each in turn.


#### Visualizing

```{R fig.height = 5, fig.width = 15}
library(ggplot2)
ggplot(Mortality_joined, aes(x = STATE, y = Heart_Disease_Deaths)) + 
  geom_bar(aes(x = STATE, y = Heart_Disease_Deaths), stat = "identity") + 
  #scale_color_manual(values = c("2019" = "purple", "2018" = "blue", "2017" = "deepskyblue1", "2016" = "green", "2015" =    "yellow", "2014" = "orange", "2005" = "red" )) +
  #geom_smooth(aes(group = YEAR), method = "loess", se=F) +
  scale_y_continuous(breaks = seq(0,600000, by = 100000)) + 
  ggtitle("Heart Disease Death Counts by State and Year") + 
  ylab("Heart Disease Death Counts") + 
  xlab("State") + 
  labs(color="Year") +
  theme_light()

#color = as.factor(YEAR)


```

Your discussion of plot 1

```{R}
ggplot(ChickWeight, aes(x = Diet)) + geom_bar(aes(y=weight), stat="summary", fun=mean)
```

Your discussion of plot 2

```{R}
# your plot 3
```

Your discussion of plot 3

#### Concluding Remarks

If any!




